name: "Manual UI Generation"

on:
  workflow_dispatch:
    inputs:
      experiment:
        description: 'Experiment directory to generate for.'
        required: false

jobs:
  find-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate UI
        uses: buildsi/spliced/action/ui@main
        with:
          experiment: ${{ github.event.inputs.experiment }}
      - name: Update Github Pages
        run: |
          printf "GitHub Actor: ${GITHUB_ACTOR}\n"
          
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git fetch
          git checkout main
          git pull origin main
          git add artifacts/*
          git add docs/_results*

          git commit -a -m "Automated push with new artifact results $(date '+%Y-%m-%d')" || exit 0
          git push origin main || echo "No new results"

