name: "Manual Pull Result Artifacts"

on:
  workflow_dispatch:
    inputs:
      runid:
        description: 'Limit to an action run id (recommended)'
        required: false

jobs:
  find-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve aritfacts
        uses: buildsi/spliced/action/artifacts@main
        with:
          runid: ${{ github.event.inputs.runid}}
          repository: buildsi/spack-splices
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate UI
        uses: buildsi/spliced/action/ui@main
      - name: Update Github Pages
        run: |
          printf "GitHub Actor: ${GITHUB_ACTOR}\n"
          
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git fetch
          git checkout main
          git add artifacts/*
          git add docs/_results*

          git commit -a -m "Automated push with new artifact results $(date '+%Y-%m-%d')" || exit 0
          git push origin main || echo "No new results"

